### PR TITLE
move lib to src and compile on publish

### PR DESCRIPTION
**Pull request by charlierudolph**
@alexdavid @kevgo

### CODE REVIEW

**Comment by kevgo** [comment]
Awesome stuff!  :airplane: from my end

**Comment by alexdavid** [comment]
Cool, does this mean we can make `coffee-script` a dev dependency now?

**Comment by charlierudolph** [comment]
Nope, we load the mycha configuration file which is a coffee file. Thats the only spot its used

**Comment by charlierudolph** [comment]
@alexdavid I moved the spot where we require coffeescript to the proper place. 
https://github.com/Originate/mycha/pull/49/files#diff-3a682e3a4ab1af9662ae2e18dd3b8cc7R52

**Comment by alexdavid** [comment]
Awesome!
LGTM

**Pull request closed without merging**
