### PR TITLE
Kg new travis format

### PR DESCRIPTION
**Pull request by kevgo**
Why aren't we using this simpler Travis config format?

### CODE REVIEW

**Comment by charlierudolph** [comment]
Previously node 4 only ran the feature tests instead of running the linting / unit tests. With this update that changes.

Also, I like the idea that the keys were in alpha order which this undoes. Doesn't matter too much since there are so few keys.

**Comment by kevgo** [comment]
@charlierudolph addressed your comments. I think the "sudo" setting is no longer necessary, since Travis runs everything inside Docker if you don't tell it anything. Adds Node 7 to the build matrix.

**Comment by charlierudolph** [comment]
I think `sudo: false` is needed in order to use the container based architecture. https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments. This repo was started in 2013 and thus we have the sudo-enabled environment as the default.

**Comment by kevgo** [comment]
Okay, I added the `sudo: false` thing back. It does no harm afaik.

**Pull request closed without merging**
