### PR TITLE
use peer dependencies

### PR DESCRIPTION
**Pull request by charlierudolph**
@alexdavid @kevgo 

Make chai, sinon and sinon-chai peer dependencies.

Just hit a very weird bug where the repo had chai, chai-subset, and mycha as devDependencies.
The chai devDependency was different from mycha's chai dependency so doing 
```coffeescript
chai.use require 'chai-subset' 
```
was doing nothing as the global expect was mycha's chai and not the chai that chai-subset was added to. 
Had to lock down to a version of mycha that used the same chai.

By pushing the dependencies to peers it keeps them as required but allows the user to properly add plugins.

### CODE REVIEW

**Comment by kevgo** [comment]
Great idea! Should we use that for all other libraries as well?

**Comment by charlierudolph** [comment]
If we do something like this I think we need to expose the test helper that sets up the globals. Otherwise you have chai/sinon/sinon-chai as devDependencies and don't see used anywhere. (dependency-lint would notice this). 

What do you guys think about not having chai / sinon / sinon-chai as dependencies or peerDependencies and instead just having a `mycha --install` command that installs the three and creates the test helper file?

**Comment by kevgo** [comment]
We use chai for the Mycha tests themselves, so if they were a dependency that would work. Why can't we keep them as normal dependencies?

**Comment by charlierudolph** [comment]
Chai can be a devDependency of mycha. I'm saying don't list it as a dependency or peerDependency. 

Extending chai is not stable with the current setup. Let's say mycha is a devDependency in your project. When you include a chai plugin it lists chai as a peerDependency so you need to have chai as a devDependency in your project too. If that chai is the same version as the chai provided by mycha then it works. But is they are different then the chai you extend in your project is not the global chai exposed by mycha.

**Comment by charlierudolph** [comment]
Chai can be a devDependency of mycha. I'm saying don't list it as a dependency or peerDependency. 

Extending chai is not stable with the current setup. Let's say mycha is a devDependency in your project. When you include a chai plugin it lists chai as a peerDependency so you need to have chai as a devDependency in your project too. If that chai is the same version as the chai provided by mycha then it works. But is they are different then the chai you extend in your project is not the global chai exposed by mycha.

**Comment by charlierudolph** [comment]
closing in favor of #47

**Pull request closed without merging**
