### PR TITLE
update supported node versions

### PR DESCRIPTION
**Pull request by charlierudolph**
@alexdavid @kevgo 

drop support for node 0.11 and add support for node 4.2 and 5

### CODE REVIEW

**Comment by kevgo** [comment]
Can we drop support for 0.10 as well? Besides that LGTM

**Comment by charlierudolph** [comment]
Do we have a particular cycle we want to follow with when to drop different versions?
With node's LTS, 0.10 is in maintenance mode until October 2016 which is the only reason I left it in.
https://github.com/nodejs/LTS/

**Comment by charlierudolph** [comment]
I'm fine dropping support when the version goes into maintenance mode though.

**Comment by kevgo** [comment]
On the other hand it doesn't hurt to keep it in here, and if it hurts we can take it out. If its still officially supported, we can keep it until it is decommissioned.

**Comment by alexdavid** [comment]
Yeah I think keeping 0.10 makes sense. If we're dropping support for a node version we should probably bump a major version

:ship: from me

**Comment by charlierudolph** [comment]
We are still pre-1.0. Should we jump to 1.0 or just bump a minor version?

**Comment by alexdavid** [comment]
For bumping version because we're dropping a version of node we can just bump a minor version.

But I think it's probably a good idea to go to 1.0 anyway because mycha is being used successfully in a lot of projects.

@kevgo thoughts?

**Comment by kevgo** [comment]
+1 lets go 1.0, unless we expect any major breaking API changes in the next couple of months. And even then, tracking this properly through major versions with each user having a clear indicator that things break is better than what we currently do.

**Pull request closed without merging**
